 version: '3'
 services:

  spark-master:
   image: bde2020/spark-master
   container_name: spark-master
   restart: always
   ports:
     - "8880:8080"
     - "7077:7077"
   environment:
     - INIT_DAEMON_STEP=setup_spark
     - SPARK_UI_REVERSEPROXY=true 
     - SPARK_UI_REVERSEPROXYURL=https://services.ds4h.org/spark/master
     - PYSPARK_PYTHON=python3
   networks:
     spark-cluster:
   restart: unless-stopped



  spark-worker-1:
   image: bde2020/spark-worker
   container_name: spark-worker-1
   depends_on:
     - spark-master
   restart: always
   ports:
     - "8881:8081"
   environment:
     - SPARK_MASTER=spark://spark-master:7077
     - SPARK_UI_REVERSEPROXY=true 
     - SPARK_UI_REVERSEPROXYURL=https://services.ds4h.org/spark/node2     
     - PYSPARK_PYTHON=python3
   networks:
     spark-cluster:



  spark-worker-2:
   image: bde2020/spark-worker
   container_name: spark-worker-2
   depends_on:
     - spark-master
   restart: always
   ports:
     - "8882:8081"
   environment:
     - SPARK_MASTER=spark://spark-master:7077
     - SPARK_UI_REVERSEPROXY=true 
     - SPARK_UI_REVERSEPROXYURL=https://services.ds4h.org/spark/node2     
     - SPARK_MASTER_WEBUI_PORT=8082
     - PYSPARK_PYTHON=python3
   networks:
     spark-cluster:




 networks:
    spark-cluster:
               
